export const SIGNED_IN = 'SIGNED_IN';
export const PASSING_BOOK_DATA = 'PASSING_BOOK_DATA';
export const GET_PAYMENT_METHOD = 'GET_PAYMENT_METHOD';
export const GET_AIRLINE_DATA = 'GET_AIRLINE_DATA';
export const GET_AIRPORT_DATA = 'GET_AIRPORT_DATA';
export const GET_HOTEL_DATA = 'GET_HOTEL_DATA';
export const GET_LUGGAGE_DATA = 'GET_LUGGAGE_DATA';